### ISSUE TITLE
Create from string fails

### ISSUE THREAD

**Issue by Klayflash** [lycantropos/cfractions#1]
Hello.

Following code
`Fraction("1/2")`
is failed with
`TypeError: Single argument should be either an integer, a floating point or a rational number.`

Standard python's Fraction is able to create from string.

**Comment by lycantropos** [comment]
Thanks for noticing, I've never used this functionality, so was not interested in implementing it because Python C API doesn't have support for regular expressions and writing a custom parser was too much for a feature that I'm not gonna use.

As a workaround you can subclass and add this functionality on your side (e.g. by calling `fractions.Fraction` and then sending `numerator` & `denominator` to a `cfractions.Fraction` constructor).

Or if you have some ideas about implementing this in plain C -- will be glad to discuss.

**Comment by Klayflash** [comment]
Thanks for quick reply!

I've implemented it without regular expressions via:
```
from cfractions import Fraction

def fractionFromStr(inStr:str) -> Fraction:
    arr = inStr.split("/")
    if len(arr) == 1:
        return Fraction(int(arr[0]))
    if len(arr) == 2:
        return Fraction(int(arr[0]),int(arr[1]))
    raise Exception("Can't create Fraction from string: {}".format(inStr))
```
I think this function can be ported to C as last resort into src/cfractions.c -> Fraction_new

**Comment by Klayflash** [comment]
Sorry about complex implementation.
Here shorter. It's slower than pure C but slower is better than nothing. 

```
from __future__ import annotations

from cfractions import Fraction
from fractions import Fraction as StdFraction

def fractionFromStr(inStr:str) -> Fraction:
    return Fraction(StdFraction(inStr))
```

**Comment by lycantropos** [comment]
> Sorry about complex implementation.
> Here shorter. It's slower than pure C but slower is better than nothing.
> 
> ```
> from __future__ import annotations
> 
> from cfractions import Fraction
> from fractions import Fraction as StdFraction
> 
> def fractionFromStr(inStr:str) -> Fraction:
>     return Fraction(StdFraction(inStr))
> ```

The main problem is that it requires a lot of work to write pure C equivalent even for [this regex](https://github.com/python/cpython/blob/efe7d08d178a7c09bcca994f2068b019c8633d83/Lib/fractions.py#L23). I'm not telling that it's impossible, but it requires extra scrupulous work that can be easily done on a client's side. I will be happy to review and provide guidance for pull request though.

**Comment by Klayflash** [comment]
I don't understand. Why just not call `fractions.Fraction` constructor from C-api and then convert the `fractions.Fraction` to cfractions.Fraction?
`fractions.Fraction` will do all regexp work...

**Comment by lycantropos** [comment]
Because the whole idea of this project is to provide faster version of fractions.Fraction and we can't do that by decorating it obviously

**Comment by Klayflash** [comment]
I propose the decoration only from string conversion case.

**Comment by Klayflash** [comment]
The following implementation is 8x times faster than fractions.Fraction on "123" and "123/123"
```
from __future__ import annotations

from cfractions import Fraction
from fractions import Fraction as StdFraction

def fractionFromStr(inStr:str) -> Fraction:
    arr = inStr.split("/")
    if len(arr) == 2:
        return Fraction(int(arr[0]),int(arr[1]))
    try:
        return Fraction(int(inStr))
    except:
        pass
    return Fraction(StdFraction(inStr))
```

**Comment by lycantropos** [comment]
I've added this functionality to `master`, going to release in the next 3 hours after do some benchmarks

**Comment by lycantropos** [comment]
I've [released this feature](https://pypi.org/project/cfractions/1.4.0/), feel free to test it and close the issue if it works.

**Comment by Klayflash** [comment]
Works good and test passed.

But it is little slower than implementation via https://github.com/lycantropos/cfractions/issues/1#issuecomment-870352489
Test with new C-fraction:
```
from __future__ import annotations
(...)

from fractions import Fraction as StdFraction

def fractionFromStrImpl(inStr:str,expected:Fraction=None) -> None:
    if expected is None:
        result = False
        try:
            fractionFromStr(inStr)
        except:
            result = True
        if not result:
            raise Exception()
    else:
        actual = fractionFromStr(inStr)
        if actual != expected:
            raise Exception()
        actual2 = fractionFromStr(str(actual))
        if actual2 != expected:
            raise Exception()

def test_fractionFromStrSpeed(inStr:str) -> None:
    log("")
    pc = PerformanceCounter()
    for i in range(0,10000000):
        fractionFromStr(inStr)
    log("time={}".format(float(pc.asSecond())))
    
def test_fractionFromStr() -> None:
    log("")
    fractionFromStrImpl("125",Fraction(125))
    fractionFromStrImpl("125.7",Fraction(1257,10))
    fractionFromStrImpl("125.7e5",Fraction(12570000))
    fractionFromStrImpl("125.7e-5",Fraction(1257,1000000))
    fractionFromStrImpl("1/3",Fraction(1,3))
    fractionFromStrImpl("-5436",Fraction(-5436))
    fractionFromStrImpl("54362345253253985723458937259823652375623875934257923857235286959823756230946523049658723804962365",Fraction(54362345253253985723458937259823652375623875934257923857235286959823756230946523049658723804962365))
    fractionFromStrImpl("dfg",None)
    fractionFromStrImpl("0x54",None)
    
def test() -> None:
    log("")
    
    test_fractionFromStr()
    test_fractionFromStrSpeed("3244")
    test_fractionFromStrSpeed("323/5534")
    
```

Shows 
```
2021-07-21 16:56:14.395  8448             test.py:85 main app started
2021-07-21 16:56:14.438  8448              test.py:8 test
2021-07-21 16:56:14.439  8448   fractions_test.py:43 test
2021-07-21 16:56:14.440  8448   fractions_test.py:31 test_fractionFromStr
2021-07-21 16:56:14.441  8448   fractions_test.py:24 test_fractionFromStrSpeed
2021-07-21 16:56:18.519  8448   fractions_test.py:28 test_fractionFromStrSpeed time=4.078
2021-07-21 16:56:18.520  8448   fractions_test.py:24 test_fractionFromStrSpeed
2021-07-21 16:56:24.718  8448   fractions_test.py:28 test_fractionFromStrSpeed time=6.187
2021-07-21 16:56:24.719  8448             test.py:93 main app tests are completed successfully in 00:00:10.328
```
while implementation from https://github.com/lycantropos/cfractions/issues/1#issuecomment-870352489
shows
```
2021-07-21 17:01:42.660 12592             test.py:85 main app started
2021-07-21 17:01:42.703 12592              test.py:8 test
2021-07-21 17:01:42.704 12592   fractions_test.py:43 test
2021-07-21 17:01:42.704 12592   fractions_test.py:31 test_fractionFromStr
2021-07-21 17:01:42.705 12592   fractions_test.py:24 test_fractionFromStrSpeed
2021-07-21 17:01:45.950 12592   fractions_test.py:28 test_fractionFromStrSpeed time=3.235
2021-07-21 17:01:45.951 12592   fractions_test.py:24 test_fractionFromStrSpeed
2021-07-21 17:01:50.882 12592   fractions_test.py:28 test_fractionFromStrSpeed time=4.937
2021-07-21 17:01:50.884 12592             test.py:93 main app tests are completed successfully in 00:00:08.219
```

**Comment by lycantropos** [comment]
In this [answer](https://stackoverflow.com/questions/8854237/faster-fractions-module-in-python/67821911#67821911) I have a plot showing how it behaves at scale for pseudo-random strings and in all cases it's not slower than `fractions.Fraction` but your benchmarks I don't understand.

**Comment by Klayflash** [comment]
You can always run fractionFromStr by your benchmark see results. I just wrote that it is little faster than cfractions.Fraction and provided the code that shows it.

I have no more issues for this ticket. So, it can be closed.
